var productJSON=`
[
{
"id":1,
"name":"Air Force 2 Sneaker",
"category":"Footware",
"subCategory":"Trainer",
"brand":"Nike",
"size":40,
"color":"black",
"price":150,
"discount":0.0,
"image":"nike casual1.jpg",
"stock":50,
"description":"Designed by Master Juno",
"date":"2025-11",
"gender":"men"
},
{
"id":2,
"name":"Air Force 1 Sneaker",
"category":"Footware",
"subCategory":"Trainer",
"brand":"Nike",
"size":42,
"color":"Brown",
"price":120,
"discount":0.0,
"image":"nike trainer1.jpg",
"stock":40,
"description":"Designed by Master Juno",
"date":"2025-07",
"gender":"female"
},
{
"id":3,
"name":"Compass",
"category":"Gear",
"subCategory":"Trainer",
"brand":"North face",
"size":40,
"color":"Core Black",
"price":125,
"discount":0.0,
"image":"compass.png",
"stock":43,
"description":"Designed by Master Smith",
"date":"2026-02",
"gender":"all"
}
,
{
"id":4,
"name":"Camping Tent",
"category":"Gear",
"subCategory":"Trainer",
"brand":"Camel",
"size":44,
"color":"Core Black",
"price":112,
"discount":0.0,
"image":"tent1.png",
"stock":43,
"description":"Designed by Master Smith",
"date":"2026-02",
"gender":"all"
}
,
{
"id":5,
"name":"Whit Cap",
"category":"apparel",
"subCategory":"cap",
"brand":"Nike",
"size":43,
"color":"White",
"price":50,
"discount":0.0,
"image":"cap.png",
"stock":43,
"description":"Designed by Master Smith",
"date":"2026-02",
"gender":"all"
}
,
{
"id":6,
"name":"Trench coat",
"category":"apparel",
"subCategory":"coat",
"brand":"Vans",
"size":41,
"color":"green",
"price":120,
"discount":0.0,
"image":"trench coat.png",
"stock":43,
"description":"Designed by Master Smith",
"date":"2026-02",
"gender":"all"
},
{
"id":7,
"name":"Blue Gloves",
"category":"Gear",
"subCategory":"Trainer",
"brand":"Adidas",
"size":41,
"color":"Blue",
"price":121,
"discount":0.1,
"image":"gloves1.png",
"stock":0,
"description":"Designed by Master Smith",
"date":"2026-03",
"gender":"all"
},
{
"id":8,
"name":"Black Jacket",
"category":"apparel",
"subCategory":"Trainer",
"brand":"Adidas",
"size":41,
"color":"Black",
"price":122,
"discount":0.0,
"image":"jacket1.png",
"stock":1,
"description":"Designed by Master Smith",
"date":"2026-04",
"gender":"all"
},
{
"id":9,
"name":"Treking Trouser",
"category":"apparel",
"subCategory":"trouser",
"brand":"North Face",
"size":41,
"color":"Khaki",
"price":100,
"discount":0.0,
"image":"trouser1.png",
"stock":0,
"description":"Designed by Master Smith",
"date":"2026-05",
"gender":"all"
},
{
"id":10,
"name":"Binoculars",
"category":"Gear",
"subCategory":"binoculars",
"brand":"North Face",
"size":41,
"color":"Green",
"price":200,
"discount":0.1,
"image":"green binoculars.png",
"stock":0,
"description":"Designed by Master Smith",
"date":"2026-03",
"gender":"all"
}
,
{
"id":11,
"name":"Red Chair",
"category":"Gear",
"subCategory":"chair",
"brand":"North Face",
"size":41,
"color":"Green",
"price":80,
"discount":0.1,
"image":"red chair.png",
"stock":1,
"description":"Designed by Master Smith",
"date":"2026-03",
"gender":"all"
},
{
"id":12,
"name":"Treking pole",
"category":"Gear",
"subCategory":"chair",
"brand":"North Face",
"size":41,
"color":"Brown",
"price":50,
"discount":0.1,
"image":"treking pole.png",
"stock":1,
"description":"Designed by Master Smith",
"date":"2026-03",
"gender":"all"
},
{
"id":13,
"name":"Blue Jacket",
"category":"apparel",
"subCategory":"top",
"brand":"North Face",
"size":42,
"color":"blue",
"price":65,
"discount":0.0,
"image":"blue jacket.png",
"stock":1,
"description":"Designed by Master Smith",
"date":"2026-03",
"gender":"all"
},
{
"id":14,
"name":"Helmet",
"category":"gear",
"subCategory":"hat",
"brand":"North Face",
"size":40,
"color":"Yellow",
"price":60,
"discount":0.0,
"image":"helmet.png",
"stock":10,
"description":"Designed by Master Smith",
"date":"2026-03",
"gender":"male"
},
{
"id":15,
"name":"Compact Trekking Essentials Kit",
"category":"gear",
"subCategory":"gear",
"brand":"North Face",
"size":40,
"color":"Yellow",
"price":50,
"discount":0.0,
"image":"compact Trekking Essentials Kit.png",
"stock":10,
"description":"Designed by Master Smith",
"date":"2026-03",
"gender":"male"
},
{
"id":16,
"name":"Merrell Hiking Shoes",
"category":"Footware",
"subCategory":"Hiking",
"brand":"North Face",
"size":40,
"color":"Black",
"price":50,
"discount":0.0,
"image":"Merrell Hiking Shoes.png",
"stock":10,
"description":"Designed by Master Smith",
"date":"2026-03",
"gender":"male"
},
{
"id":17,
"name":"Snorkel",
"category":"gear",
"subCategory":"sea",
"brand":"North Face",
"size":40,
"color":"blue",
"price":40,
"discount":0.0,
"image":"snorkel.png",
"stock":10,
"description":"Designed by Master Smith",
"date":"2026-03",
"gender":"all"
},
{
"id":18,
"name":"3 pairs of socks",
"category":"Footware",
"subCategory":"hiking",
"brand":"North Face",
"size":40,
"color":"blue",
"price":40,
"discount":0.0,
"image":"socks.png",
"stock":10,
"description":"Designed by Master Smith",
"date":"2026-03",
"gender":"all"
}
]
`;